name = "indo-talent-erp"
main = "cloudflare/index.js"
compatibility_date = "2026-08-26"

[triggers]
routes = ["https://screening.indo-talent.my.id/api/*"]

[build]
command = "npm install && npm run build"
